//! Turns the artifacts in `bin/` into something the crate can use.
//!
//! Two jobs. It generates the program layout, so the list of commands a sandbox offers comes
//! from the images that actually shipped rather than from a table someone has to maintain. And
//! on `wasm32` it points the linker at the prebuilt archive that holds the compiled-in
//! programs, so a consumer needs no C toolchain, no wabt and no wasi-sdk.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap_or_default());
    let bin = manifest.join("../../bin");
    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap_or_default());
    println!("cargo:rerun-if-changed={}", bin.display());

    let images = ["busybox", "jq"];
    let mut generated = String::new();
    generated.push_str("// Generated by build.rs from bin/. Do not edit.\n");
    generated.push_str("pub(crate) static LAYOUT: &[Layout] = &[\n");
    for image in images {
        let commands = bin.join(format!("{image}.commands"));
        let wasm = bin.join(format!("{image}.wasm"));
        if !commands.exists() || !wasm.exists() {
            continue;
        }
        let text = std::fs::read_to_string(&commands).unwrap_or_default();
        let _ = writeln!(generated, "    Layout {{ image: {image:?}, commands: &[");
        for line in text.lines() {
            let mut fields = line.split('\t');
            let (Some(name), Some(path)) = (fields.next(), fields.next()) else {
                continue;
            };
            if name.is_empty() || !path.starts_with('/') {
                continue;
            }
            let _ = writeln!(
                generated,
                "        Command {{ name: {name:?}, path: {path:?} }},"
            );
        }
        generated.push_str("    ] },\n");
    }
    generated.push_str("];\n\n");

    // The bytes, for the interpreter backend. Only compiled in when that feature is on, so a
    // production build that uses the compiled-in programs pays nothing for them.
    generated.push_str(
        "#[cfg(feature = \"interp\")]\npub(crate) static IMAGES: &[(&str, &[u8])] = &[\n",
    );
    for image in images {
        let wasm = bin.join(format!("{image}.wasm"));
        if wasm.exists() {
            let _ = writeln!(
                generated,
                "    ({image:?}, include_bytes!({:?})),",
                wasm.display()
            );
        }
    }
    generated.push_str("];\n");
    let _ = std::fs::write(out.join("programs.rs"), generated);

    // The compiled-in programs are wasm32 objects: they can only be linked into a wasm32
    // build, which is why the AOT backend is not available natively.
    let target = std::env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    let has_aot = std::env::var("CARGO_FEATURE_AOT").is_ok();
    if target == "wasm32" && has_aot {
        let archive = find_archive(&bin);
        match archive {
            Some(path) => {
                println!("cargo:rustc-link-search=native={}", path.display());
                println!("cargo:rustc-link-lib=static=wasmux-images");
                println!("cargo:rustc-cfg=wasmux_aot_linked");
            }
            None => {
                println!(
                    "cargo:warning=wasmux: bin/libwasmux-images.a is missing, so the compiled-in \
                     backend is unavailable and the interpreter will run the programs instead — \
                     correct, about ten times slower. The archive is deliberately not \
                     distributed (it would combine GPL-2.0-only and Apache-2.0 code in one \
                     binary; see THIRD-PARTY.md). Build it with `toolchain/build-archive.sh` in \
                     a wasmux checkout, or keep the `interp` feature on and ignore this."
                );
            }
        }
    }
}

fn find_archive(bin: &Path) -> Option<PathBuf> {
    if bin.join("libwasmux-images.a").exists() {
        return Some(bin.to_path_buf());
    }
    None
}
