//! Name resolution: turning what a guest typed into something the kernel can act on.
//!
//! Three kinds of thing share one namespace, and this module is where they are told apart:
//!
//! * **Programs.** `/bin/sh` and its siblings are not files. They are entries in the
//!   sandbox's program table, synthesized into `/bin` and `/usr/bin` so that a shell's `PATH`
//!   search, `stat` and `execve` all behave, and so that `/proc/self/exe` can be executed
//!   again, which is how BusyBox spawns subshells without `fork`.
//! * **Devices and `/proc`.** Generated by the kernel, never by a mount.
//! * **Mounts.** Everything else, resolved against the [`Vfs`] whose mount point is the
//!   longest match, and handed a path relative to that mount point.
//!
//! Resolution is lexical first: `.` and `..` are folded away before anything is looked up, and
//! `..` at the root stays at the root. A guest therefore cannot name anything outside its
//! mounts, whatever it does with dots, and a `Vfs` never has to defend against traversal.
//! Symlinks are then followed one component at a time, up to [`MAX_HOPS`], and only for mounts
//! that say they have any.

use crate::errno::{Errno, VfsResult};
use crate::vfs::{FileType, Vfs};
use std::collections::{BTreeMap, BTreeSet};
use std::sync::Arc;

/// How many symlinks may be traversed before giving up with [`Errno::LOOP`].
pub(crate) const MAX_HOPS: u32 = 40;

/// Index of a program in the sandbox's table.
pub(crate) type ProgramId = usize;

/// A filesystem grafted into the guest's namespace at a path.
pub(crate) struct Mount {
    /// Normalized mount point: `/` or `/foo/bar`, never with a trailing slash.
    pub(crate) at: String,
    pub(crate) vfs: Arc<dyn Vfs>,
    pub(crate) read_only: bool,
}

/// The mount table, ordered so that the longest match is found first.
pub(crate) struct Mounts {
    list: Vec<Mount>,
}

impl Mounts {
    pub(crate) fn new(mut list: Vec<Mount>) -> Mounts {
        // Longest mount point first, so resolution finds the most specific one.
        list.sort_by_key(|mount| core::cmp::Reverse(mount.at.len()));
        Mounts { list }
    }

    pub(crate) fn get(&self, index: usize) -> Option<&Mount> {
        self.list.get(index)
    }

    /// The mount owning `guest`, and the path relative to its mount point.
    fn find(&self, guest: &str) -> Option<(usize, String)> {
        for (index, mount) in self.list.iter().enumerate() {
            if mount.at == "/" {
                return Some((index, guest.to_string()));
            }
            if let Some(rest) = guest.strip_prefix(&mount.at) {
                if rest.is_empty() {
                    return Some((index, "/".to_string()));
                }
                if rest.starts_with('/') {
                    return Some((index, rest.to_string()));
                }
            }
        }
        None
    }

    /// Mount points that are direct children of `guest`, so a virtual directory listing can
    /// show them: with a mount at `/work`, the root must list `work`.
    fn children_of(&self, guest: &str) -> Vec<String> {
        let prefix = if guest == "/" {
            "/".to_string()
        } else {
            format!("{guest}/")
        };
        let mut out = Vec::new();
        for mount in &self.list {
            if let Some(rest) = mount.at.strip_prefix(&prefix) {
                if !rest.is_empty() && !rest.contains('/') {
                    out.push(rest.to_string());
                }
            }
        }
        out
    }
}

/// A kernel-generated character device.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub(crate) enum Device {
    /// `/dev/null`
    Null,
    /// `/dev/zero`
    Zero,
    /// `/dev/urandom` and `/dev/random`
    Random,
    /// `/dev/tty` and `/dev/console`
    Tty,
    /// `/dev/stdin`, `/dev/stdout`, `/dev/stderr` and `/proc/self/fd/N`
    Fd(i32),
}

/// What a resolved path turned out to be.
#[derive(Debug)]
pub(crate) enum Node {
    /// A program in the sandbox's table.
    Program {
        id: ProgramId,
        /// The guest path it was found at, which becomes `/proc/self/exe`.
        guest: String,
    },
    /// A generated device.
    Device(Device),
    /// A generated text file under `/proc`. The content is produced on open.
    Synth {
        /// The full guest path, which selects the content.
        guest: String,
    },
    /// A path inside a mount.
    Mounted {
        /// Index into [`Mounts`].
        mount: usize,
        /// Path relative to the mount point, as the [`Vfs`] contract requires.
        rel: String,
        /// The full guest path.
        guest: String,
    },
    /// A directory that exists only because the kernel says so: `/`, `/bin`, `/dev`, `/proc`,
    /// and any parent of a mount point.
    VirtualDir { guest: String },
    /// A symlink the kernel generates, such as `/proc/self/exe`.
    VirtualLink {
        /// Where it points.
        target: String,
    },
}

/// The kernel's synthetic part of the namespace: which programs exist and where.
pub(crate) struct Overlay {
    /// Guest path to program table index, e.g. `/bin/sh` and `/usr/bin/jq`.
    programs: BTreeMap<String, ProgramId>,
    /// Every directory implied by a program path or a device, so `/bin` and `/usr` exist.
    dirs: BTreeSet<String>,
}

impl Overlay {
    /// Build the overlay from the program paths a sandbox was configured with.
    pub(crate) fn new(programs: BTreeMap<String, ProgramId>) -> Overlay {
        let mut dirs = BTreeSet::new();
        for dir in ["/", "/dev", "/proc", "/proc/self"] {
            dirs.insert(dir.to_string());
        }
        for path in programs.keys() {
            let mut cursor = path.as_str();
            while let Some(index) = cursor.rfind('/') {
                let parent = cursor.get(..index).unwrap_or("");
                dirs.insert(if parent.is_empty() {
                    "/".to_string()
                } else {
                    parent.to_string()
                });
                cursor = parent;
                if cursor.is_empty() {
                    break;
                }
            }
        }
        Overlay { programs, dirs }
    }

    pub(crate) fn program(&self, guest: &str) -> Option<ProgramId> {
        self.programs.get(guest).copied()
    }

    /// Entries of a virtual directory: programs, devices and `/proc` names that live here.
    fn entries_in(&self, guest: &str) -> Vec<(String, FileType)> {
        let prefix = if guest == "/" {
            "/".to_string()
        } else {
            format!("{guest}/")
        };
        let mut out: Vec<(String, FileType)> = Vec::new();
        for path in self.programs.keys() {
            if let Some(rest) = path.strip_prefix(&prefix) {
                if !rest.is_empty() && !rest.contains('/') {
                    out.push((rest.to_string(), FileType::File));
                }
            }
        }
        for dir in &self.dirs {
            if let Some(rest) = dir.strip_prefix(&prefix) {
                if !rest.is_empty() && !rest.contains('/') {
                    out.push((rest.to_string(), FileType::Dir));
                }
            }
        }
        match guest {
            "/dev" => {
                for name in [
                    "null", "zero", "urandom", "random", "tty", "console", "stdin", "stdout",
                    "stderr",
                ] {
                    out.push((name.to_string(), FileType::File));
                }
            }
            "/proc" => {
                for name in PROC_FILES {
                    out.push((name.to_string(), FileType::File));
                }
                out.push(("self".to_string(), FileType::Dir));
            }
            "/proc/self" => {
                for name in ["exe", "cwd", "cmdline", "comm", "stat", "fd"] {
                    out.push((name.to_string(), FileType::File));
                }
            }
            _ => {}
        }
        out.sort();
        out.dedup();
        out
    }

    fn is_dir(&self, guest: &str) -> bool {
        self.dirs.contains(guest) || guest == "/proc/self/fd"
    }
}

/// Generated files directly under `/proc`.
pub(crate) const PROC_FILES: &[&str] = &[
    "cpuinfo",
    "meminfo",
    "uptime",
    "version",
    "mounts",
    "filesystems",
    "loadavg",
    "stat",
];

/// What the resolver needs to know about the process asking.
pub(crate) struct Who<'a> {
    pub(crate) cwd: &'a str,
    /// `/proc/self/exe` for this process.
    pub(crate) exe: &'a str,
    pub(crate) pid: i32,
}

/// Fold a path into absolute, normalized components.
///
/// `base` is used when `path` is relative. `.` disappears, `..` pops, and popping past the
/// root is a no-op, which is what makes escape impossible.
pub(crate) fn normalize(base: &str, path: &str) -> Vec<String> {
    let mut parts: Vec<String> = Vec::new();
    if !path.starts_with('/') {
        for component in base.split('/') {
            if !component.is_empty() && component != "." {
                if component == ".." {
                    parts.pop();
                } else {
                    parts.push(component.to_string());
                }
            }
        }
    }
    for component in path.split('/') {
        match component {
            "" | "." => {}
            ".." => {
                parts.pop();
            }
            other => parts.push(other.to_string()),
        }
    }
    parts
}

/// Join normalized components back into a guest path.
pub(crate) fn join(parts: &[String]) -> String {
    if parts.is_empty() {
        "/".to_string()
    } else {
        let mut out = String::with_capacity(parts.iter().map(|p| p.len().saturating_add(1)).sum());
        for part in parts {
            out.push('/');
            out.push_str(part);
        }
        out
    }
}

/// Everything resolution needs, gathered so the resolver can be tested on its own.
pub(crate) struct Resolver<'a> {
    pub(crate) overlay: &'a Overlay,
    pub(crate) mounts: &'a Mounts,
}

impl<'a> Resolver<'a> {
    /// Resolve `path` for the process described by `who`.
    ///
    /// With `follow_last` false, a symlink in the final position is returned as
    /// [`Node::VirtualLink`] or as the mounted symlink itself, which is what `lstat`,
    /// `readlink` and `unlink` need.
    pub(crate) fn resolve(
        &self,
        who: &Who<'_>,
        base: &str,
        path: &str,
        follow_last: bool,
    ) -> VfsResult<Node> {
        if path.len() > super::mem::Mem::MAX_STR {
            return Err(Errno::NAMETOOLONG);
        }
        let mut parts = normalize(base, path);
        let mut hops = 0u32;
        // Left to right, one component at a time. A symlink splices its target in and the walk
        // starts again, which is what makes a link to a link, or to a relative path, work.
        let mut index = 0usize;
        loop {
            if index >= parts.len() {
                return self.classify_final(who, &join(&parts));
            }
            let next = index.saturating_add(1);
            let here = join(parts.get(..next).unwrap_or(&[]));
            let is_final = next >= parts.len();
            // An intermediate component is always followed; the last one only on request.
            if !is_final || follow_last {
                if let Some(target) = self.symlink_target(who, &here)? {
                    hops = hops.saturating_add(1);
                    if hops > MAX_HOPS {
                        return Err(Errno::LOOP);
                    }
                    let tail: Vec<String> = parts.get(next..).unwrap_or(&[]).to_vec();
                    let parent = join(parts.get(..index).unwrap_or(&[]));
                    let mut rebuilt = if target.starts_with('/') {
                        normalize("/", &target)
                    } else {
                        normalize(&parent, &target)
                    };
                    rebuilt.extend(tail);
                    parts = rebuilt;
                    index = 0;
                    continue;
                }
            } else if let Some(target) = self.virtual_link(who, &here) {
                // `readlink` and `lstat` of one of the kernel's own symlinks.
                return Ok(Node::VirtualLink { target });
            }
            index = next;
        }
    }

    /// Classify without any symlink following.
    fn classify_final(&self, who: &Who<'_>, guest: &str) -> VfsResult<Node> {
        if let Some(id) = self.overlay.program(guest) {
            return Ok(Node::Program {
                id,
                guest: guest.to_string(),
            });
        }
        if let Some(device) = device_of(guest) {
            return Ok(Node::Device(device));
        }
        if let Some(node) = self.proc_node(who, guest) {
            return Ok(node);
        }
        if let Some((mount, rel)) = self.mounts.find(guest) {
            // A directory the kernel invents, `/bin` or `/proc`, only shadows a mount when the
            // mount has nothing there. Where both have it, the mount wins and the listing is
            // merged, so a real `/usr` full of the caller's files is not hidden by `/usr/bin`.
            if guest != "/" && self.overlay.is_dir(guest) {
                let exists = match self.mounts.get(mount) {
                    Some(m) => match m.vfs.stat(&rel, true) {
                        Ok(stat) => stat.file_type == FileType::Dir,
                        Err(Errno::AGAIN) => return Err(Errno::AGAIN),
                        Err(_) => false,
                    },
                    None => false,
                };
                if !exists {
                    return Ok(Node::VirtualDir {
                        guest: guest.to_string(),
                    });
                }
            }
            return Ok(Node::Mounted {
                mount,
                rel,
                guest: guest.to_string(),
            });
        }
        if self.overlay.is_dir(guest) || self.is_mount_parent(guest) {
            return Ok(Node::VirtualDir {
                guest: guest.to_string(),
            });
        }
        Err(Errno::NOENT)
    }

    fn is_mount_parent(&self, guest: &str) -> bool {
        !self.mounts.children_of(guest).is_empty()
    }

    /// `/proc` paths the kernel generates. `/proc/<own pid>/x` is treated as `/proc/self/x`.
    fn proc_node(&self, who: &Who<'_>, guest: &str) -> Option<Node> {
        let rest = guest.strip_prefix("/proc/")?;
        let own = who.pid.to_string();
        let rest = rest
            .strip_prefix(own.as_str())
            .and_then(|r| r.strip_prefix('/'))
            .unwrap_or(rest);
        let rest = rest.strip_prefix("self/").unwrap_or(rest);
        if rest == "fd" {
            return Some(Node::VirtualDir {
                guest: guest.to_string(),
            });
        }
        if let Some(number) = rest.strip_prefix("fd/") {
            let fd: i32 = number.parse().ok()?;
            return Some(Node::Device(Device::Fd(fd)));
        }
        if PROC_FILES.contains(&rest) || matches!(rest, "cmdline" | "comm" | "stat" | "status") {
            return Some(Node::Synth {
                guest: guest.to_string(),
            });
        }
        if rest.is_empty() || rest == "self" {
            return Some(Node::VirtualDir {
                guest: guest.to_string(),
            });
        }
        None
    }

    /// The target of a symlink at `guest`, virtual or from a mount, if it is one.
    fn symlink_target(&self, who: &Who<'_>, guest: &str) -> VfsResult<Option<String>> {
        if let Some(target) = self.virtual_link(who, guest) {
            return Ok(Some(target));
        }
        // Programs, devices and /proc files are never symlinks; skip the mount probe.
        if self.overlay.program(guest).is_some() || device_of(guest).is_some() {
            return Ok(None);
        }
        let Some((index, rel)) = self.mounts.find(guest) else {
            return Ok(None);
        };
        let Some(mount) = self.mounts.get(index) else {
            return Ok(None);
        };
        // A filesystem without symlinks is not asked, which spares an object store two round
        // trips per path component.
        if !mount.vfs.has_symlinks() {
            return Ok(None);
        }
        match mount.vfs.stat(&rel, false) {
            Ok(stat) if stat.file_type == FileType::Symlink => match mount.vfs.readlink(&rel) {
                Ok(target) => Ok(Some(target)),
                Err(Errno::AGAIN) => Err(Errno::AGAIN),
                Err(_) => Ok(None),
            },
            Err(Errno::AGAIN) => Err(Errno::AGAIN),
            _ => Ok(None),
        }
    }

    /// The symlinks the kernel invents.
    fn virtual_link(&self, who: &Who<'_>, guest: &str) -> Option<String> {
        let own = format!("/proc/{}", who.pid);
        let tail = guest
            .strip_prefix("/proc/self")
            .or_else(|| guest.strip_prefix(own.as_str()));
        match tail {
            Some("/exe") => return Some(who.exe.to_string()),
            Some("/cwd") => return Some(who.cwd.to_string()),
            _ => {}
        }
        match guest {
            "/dev/stdin" => Some("/proc/self/fd/0".to_string()),
            "/dev/stdout" => Some("/proc/self/fd/1".to_string()),
            "/dev/stderr" => Some("/proc/self/fd/2".to_string()),
            _ => None,
        }
    }

    /// Everything that should appear in a virtual directory listing at `guest`.
    pub(crate) fn virtual_entries(&self, guest: &str) -> Vec<(String, FileType)> {
        let mut out = self.overlay.entries_in(guest);
        for name in self.mounts.children_of(guest) {
            out.push((name, FileType::Dir));
        }
        out.sort();
        out.dedup();
        out
    }
}

fn device_of(guest: &str) -> Option<Device> {
    match guest {
        "/dev/null" => Some(Device::Null),
        "/dev/zero" => Some(Device::Zero),
        "/dev/urandom" | "/dev/random" => Some(Device::Random),
        "/dev/tty" | "/dev/console" => Some(Device::Tty),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::vfs::MemVfs;

    fn overlay() -> Overlay {
        let mut programs = BTreeMap::new();
        programs.insert("/bin/sh".to_string(), 0);
        programs.insert("/bin/ls".to_string(), 0);
        programs.insert("/usr/bin/jq".to_string(), 1);
        Overlay::new(programs)
    }

    fn mounts() -> Mounts {
        Mounts::new(vec![
            Mount {
                at: "/".to_string(),
                vfs: Arc::new(MemVfs::new().with_dir("/home")),
                read_only: false,
            },
            Mount {
                at: "/work".to_string(),
                vfs: Arc::new(MemVfs::new().with_file("/a.txt", b"x")),
                read_only: true,
            },
        ])
    }

    fn who() -> Who<'static> {
        Who {
            cwd: "/home",
            exe: "/bin/sh",
            pid: 7,
        }
    }

    #[test]
    fn normalization_folds_dots_and_cannot_escape() {
        let cases = [
            ("/", "a/b", "/a/b"),
            ("/x", "y", "/x/y"),
            ("/x/y", "../z", "/x/z"),
            ("/", "../../../etc/passwd", "/etc/passwd"),
            ("/", "/a/./b/../c", "/a/c"),
            ("/", "///a////b//", "/a/b"),
            ("/a/b", "..", "/a"),
            ("/", "..", "/"),
            ("/", ".", "/"),
            ("/", "", "/"),
        ];
        for (base, path, expected) in cases {
            assert_eq!(
                join(&normalize(base, path)),
                expected,
                "normalize({base:?}, {path:?})"
            );
        }
    }

    #[test]
    fn programs_shadow_mounts_and_carry_their_id() {
        let (o, m) = (overlay(), mounts());
        let r = Resolver {
            overlay: &o,
            mounts: &m,
        };
        match r.resolve(&who(), "/", "/bin/sh", true) {
            Ok(Node::Program { id, guest }) => {
                assert_eq!(id, 0);
                assert_eq!(guest, "/bin/sh");
            }
            other => panic!("expected a program, got {other:?}"),
        }
        assert!(matches!(
            r.resolve(&who(), "/", "/usr/bin/jq", true),
            Ok(Node::Program { id: 1, .. })
        ));
        assert!(matches!(
            r.resolve(&who(), "/", "/bin", true),
            Ok(Node::VirtualDir { .. })
        ));
        assert!(matches!(
            r.resolve(&who(), "/", "/usr", true),
            Ok(Node::VirtualDir { .. })
        ));
    }

    #[test]
    fn the_longest_mount_wins_and_paths_are_relative_to_it() {
        let (o, m) = (overlay(), mounts());
        let r = Resolver {
            overlay: &o,
            mounts: &m,
        };
        match r.resolve(&who(), "/", "/work/a.txt", true) {
            Ok(Node::Mounted { mount, rel, guest }) => {
                assert_eq!(m.get(mount).map(|x| x.at.as_str()), Some("/work"));
                assert_eq!(
                    rel, "/a.txt",
                    "the Vfs sees a path relative to its mount point"
                );
                assert_eq!(guest, "/work/a.txt");
            }
            other => panic!("expected a mounted file, got {other:?}"),
        }
        match r.resolve(&who(), "/", "/home/x", true) {
            Ok(Node::Mounted { mount, rel, .. }) => {
                assert_eq!(m.get(mount).map(|x| x.at.as_str()), Some("/"));
                assert_eq!(rel, "/home/x");
            }
            other => panic!("expected the root mount, got {other:?}"),
        }
    }

    #[test]
    fn dot_dot_cannot_reach_out_of_a_mount() {
        let (o, m) = (overlay(), mounts());
        let r = Resolver {
            overlay: &o,
            mounts: &m,
        };
        // From inside /work, climbing out lands in the root mount, never outside the sandbox.
        match r.resolve(
            &Who {
                cwd: "/work",
                exe: "/bin/sh",
                pid: 7,
            },
            "/work",
            "../../../etc",
            true,
        ) {
            Ok(Node::Mounted { rel, guest, .. }) => {
                assert_eq!(guest, "/etc");
                assert_eq!(rel, "/etc");
            }
            other => panic!("expected /etc in the root mount, got {other:?}"),
        }
    }

    #[test]
    fn proc_self_exe_is_a_symlink_to_the_program() {
        let (o, m) = (overlay(), mounts());
        let r = Resolver {
            overlay: &o,
            mounts: &m,
        };
        // Followed: the program itself, which is what makes BusyBox's re-exec work.
        assert!(matches!(
            r.resolve(&who(), "/", "/proc/self/exe", true),
            Ok(Node::Program { id: 0, .. })
        ));
        // Not followed: the link, which is what readlink reports.
        match r.resolve(&who(), "/", "/proc/self/exe", false) {
            Ok(Node::VirtualLink { target }) => assert_eq!(target, "/bin/sh"),
            other => panic!("expected a virtual link, got {other:?}"),
        }
        // The process's own pid is an alias for self.
        assert!(matches!(
            r.resolve(&who(), "/", "/proc/7/exe", true),
            Ok(Node::Program { .. })
        ));
    }

    #[test]
    fn devices_and_proc_files_resolve() {
        let (o, m) = (overlay(), mounts());
        let r = Resolver {
            overlay: &o,
            mounts: &m,
        };
        assert!(matches!(
            r.resolve(&who(), "/", "/dev/null", true),
            Ok(Node::Device(Device::Null))
        ));
        assert!(matches!(
            r.resolve(&who(), "/", "/dev/urandom", true),
            Ok(Node::Device(Device::Random))
        ));
        assert!(matches!(
            r.resolve(&who(), "/", "/dev/stdout", true),
            Ok(Node::Device(Device::Fd(1)))
        ));
        assert!(matches!(
            r.resolve(&who(), "/", "/proc/self/fd/2", true),
            Ok(Node::Device(Device::Fd(2)))
        ));
        assert!(matches!(
            r.resolve(&who(), "/", "/proc/meminfo", true),
            Ok(Node::Synth { .. })
        ));
        assert!(matches!(
            r.resolve(&who(), "/", "/proc/self/cmdline", true),
            Ok(Node::Synth { .. })
        ));
    }

    #[test]
    fn mount_symlinks_are_followed_including_in_the_middle() {
        let fs = MemVfs::new().with_file("/real/file", b"hi");
        fs.symlink("/real", "/link").unwrap();
        let m = Mounts::new(vec![Mount {
            at: "/".to_string(),
            vfs: Arc::new(fs),
            read_only: false,
        }]);
        let o = overlay();
        let r = Resolver {
            overlay: &o,
            mounts: &m,
        };
        match r.resolve(&who(), "/", "/link/file", true) {
            Ok(Node::Mounted { guest, .. }) => assert_eq!(guest, "/real/file"),
            other => panic!("expected the symlink to be followed, got {other:?}"),
        }
    }

    #[test]
    fn a_symlink_loop_ends_in_eloop() {
        let fs = MemVfs::new();
        fs.symlink("/b", "/a").unwrap();
        fs.symlink("/a", "/b").unwrap();
        let m = Mounts::new(vec![Mount {
            at: "/".to_string(),
            vfs: Arc::new(fs),
            read_only: false,
        }]);
        let o = overlay();
        let r = Resolver {
            overlay: &o,
            mounts: &m,
        };
        assert_eq!(r.resolve(&who(), "/", "/a", true).err(), Some(Errno::LOOP));
    }

    #[test]
    fn a_root_listing_shows_mounts_and_program_directories() {
        let (o, m) = (overlay(), mounts());
        let r = Resolver {
            overlay: &o,
            mounts: &m,
        };
        let names: Vec<String> = r.virtual_entries("/").into_iter().map(|(n, _)| n).collect();
        for expected in ["bin", "dev", "proc", "usr", "work"] {
            assert!(
                names.contains(&expected.to_string()),
                "{expected} missing from {names:?}"
            );
        }
        let bin: Vec<String> = r
            .virtual_entries("/bin")
            .into_iter()
            .map(|(n, _)| n)
            .collect();
        assert_eq!(bin, vec!["ls".to_string(), "sh".to_string()]);
    }

    #[test]
    fn an_overlong_path_is_rejected() {
        let (o, m) = (overlay(), mounts());
        let r = Resolver {
            overlay: &o,
            mounts: &m,
        };
        let long = format!("/{}", "a".repeat(5000));
        assert_eq!(
            r.resolve(&who(), "/", &long, true).err(),
            Some(Errno::NAMETOOLONG)
        );
    }
}
