#!/usr/bin/env bash
# Compiles bin/*.wasm into bin/libwasmux-images.a, the archive the `aot` backend links.
#
# `wasm2c` translates each program to C; that C plus wasm2c's runtime plus csrc/glue.c is
# compiled for wasm32-wasip2 and archived. The crate's build.rs finds the archive and links
# it, so a consumer needs no C toolchain: this runs once, here, and the result is checked in.
#
# Needs: wasm2c (wabt) and a wasi-sdk. Point at them with:
#
#   WABT=/path/to/wabt-1.0.41  WASI_SDK=/path/to/wasi-sdk-34.0  ./toolchain/build-archive.sh
#
# Both default to toolchain/build/tools/*, where fetch-tools.sh puts them.
set -euo pipefail

HERE=$(cd "$(dirname "$0")" && pwd)
ROOT=$(cd "$HERE/.." && pwd)
WORK=$HERE/build
OUT=$ROOT/bin
JOBS=$(nproc 2>/dev/null || echo 4)

WABT=${WABT:-$(echo "$WORK"/tools/wabt-*)}
WASI_SDK=${WASI_SDK:-$(echo "$WORK"/tools/wasi-sdk-*)}
TARGET=${TARGET:-wasm32-wasip2}

W2C=$WABT/bin/wasm2c
CC=$WASI_SDK/bin/clang
AR=$WASI_SDK/bin/llvm-ar

# Two layouts, because the two ways of getting wabt disagree. A release tarball installs the
# wasm2c runtime under `share/wabt/wasm2c` with the public headers in `include`; a source
# checkout keeps both in `wasm2c/`. Look for the implementation, then find the headers
# wherever `wasm-rt.h` actually is.
if [ -f "$WABT/share/wabt/wasm2c/wasm-rt-impl.c" ]; then
  RT=$WABT/share/wabt/wasm2c
  RT_INCLUDE=$WABT/include
elif [ -f "$WABT/wasm2c/wasm-rt-impl.c" ]; then
  RT=$WABT/wasm2c
  RT_INCLUDE=$WABT/wasm2c
else
  echo "no wasm2c runtime under $WABT (looked in share/wabt/wasm2c and wasm2c)" >&2
  exit 2
fi

for needed in "$W2C" "$RT_INCLUDE/wasm-rt.h" "$RT/wasm-rt-impl.c" "$CC" "$AR"; do
  [ -e "$needed" ] || { echo "missing: $needed (set WABT and WASI_SDK)" >&2; exit 2; }
done

GEN=$WORK/images
mkdir -p "$GEN" "$WORK/obj"

# Which programs to compile in: every image in bin/.
images=()
for wasm in "$OUT"/*.wasm; do
  [ -e "$wasm" ] || continue
  images+=("$(basename "$wasm" .wasm)")
done
[ ${#images[@]} -gt 0 ] || { echo "no images in bin/; run build-images.sh first" >&2; exit 2; }
printf 'compiling in: %s\n' "${images[*]}"

# --- 1. wasm -> C, only when the wasm is newer than the C -------------------------------
#
# --num-outputs splits each program into translation units so they compile in parallel;
# BusyBox is about 200k lines of generated C and one unit takes minutes.
for name in "${images[@]}"; do
  if [ ! -f "$GEN/$name.h" ] || [ "$OUT/$name.wasm" -nt "$GEN/$name.h" ]; then
    echo "wasm2c $name"
    "$W2C" "$OUT/$name.wasm" -n "$name" --num-outputs=8 -o "$GEN/$name.c"
  fi
done

# --- 2. the generated image list --------------------------------------------------------
#
# glue.c has no hardcoded program names; it includes this.
{
  echo '/* Generated by toolchain/build-archive.sh. Do not edit. */'
  echo '#ifndef WASMUX_IMAGES_H'
  echo '#define WASMUX_IMAGES_H'
  for name in "${images[@]}"; do echo "#include \"$name.h\""; done
  printf '#define WASMUX_IMAGE_TABLE'
  sep=' '
  for name in "${images[@]}"; do printf '%sIMG(%s)' "$sep" "$name"; sep=', '; done
  echo
  echo '#endif'
} > "$GEN/wasmux-images.h"

# --- 3. compile ------------------------------------------------------------------------
#
# WASM_RT_USE_MMAP=0 with bounds checking: the consumer is itself a wasm module, so there is
# no mmap to reserve a guard region with, and every guest access is a compare and branch.
# WASM_RT_SKIP_SIGNAL_RECOVERY because there are no signals to recover from either.
# The call-depth counter is the fuse that turns a runaway guest recursion into one dead
# process instead of a host stack overflow. 400 fits inside a 1 MiB host wasm stack, which
# is what a typical component runtime allows; raise both together if you raise either.
CFLAGS=(--target="$TARGET" --sysroot="$WASI_SDK/share/wasi-sysroot" -O2
        # wasm2c's generated C carries its own path into the object through the assert
        # macros, so without this the *consumer's* binary ends up quoting whoever built the
        # archive: "/home/someone/wasmux/toolchain/build/images/busybox_0.c". Map the
        # checkout away and two people's archives also become comparable.
        -ffile-prefix-map="$(cd "$ROOT" && pwd)=wasmux"
        -ffile-prefix-map="$(cd "$WASI_SDK" && pwd)=wasi-sdk"
        -I"$RT_INCLUDE" -I"$RT" -I"$GEN" -I"$HERE/csrc" -I"$HERE/csrc/shim"
        -DWASM_RT_MEMCHECK_BOUNDS_CHECK=1
        -DWASM_RT_USE_MMAP=0
        -DWASM_RT_SKIP_SIGNAL_RECOVERY=1
        -DWASM_RT_STACK_DEPTH_COUNT=1
        -DWASM_RT_MAX_CALL_STACK_DEPTH="${WASMUX_MAX_DEPTH:-400}"
        # wasm2c emits setjmp/longjmp for its trap catcher, lowered onto wasm exceptions.
        -fwasm-exceptions -mllvm -wasm-enable-sjlj -mllvm -wasm-use-legacy-eh=false
        # wasi-sdk has no sigsetjmp; the trap catcher does not need the signal mask.
        "-Dsigsetjmp(b,s)=setjmp(b)" -Dsiglongjmp=longjmp
        -Wno-unused -Wno-unused-command-line-argument)

sources=("$HERE/csrc/glue.c" "$HERE/csrc/sjlj-rt.c"
         "$RT/wasm-rt-impl.c" "$RT/wasm-rt-mem-impl.c" "$RT/wasm-rt-exceptions-impl.c"
         "$GEN"/*_[0-9]*.c)

# An object is stale if its source is newer *or if this script is* — the flags live here, and
# a flag change that does not invalidate the objects silently produces an archive built with
# the old ones. That cost an afternoon: adding -ffile-prefix-map appeared to do nothing.
printf '%s\n' "${sources[@]}" | xargs -P "$JOBS" -I{} bash -c '
  src={}
  obj='"$WORK"'/obj/$(basename "${src%.c}").o
  if [ ! -f "$obj" ] || [ "$src" -nt "$obj" ] || [ '"$HERE"'/build-archive.sh -nt "$obj" ]; then
    "$0" "${@:1}" -c "$src" -o "$obj" || exit 1
  fi' "$CC" "${CFLAGS[@]}"

# --- 4. archive ------------------------------------------------------------------------
rm -f "$OUT/libwasmux-images.a"
"$AR" rcs "$OUT/libwasmux-images.a" "$WORK"/obj/*.o
printf 'bin/libwasmux-images.a  %s bytes\n' "$(stat -c%s "$OUT/libwasmux-images.a")"
